steps:
- name: 'gcr.io/cloud-builders/curl'
  args: ['-XPUT', '-d', '{ "repoName": "$REPO_NAME", "status": "RUNNING", "buildId": "$BUILD_ID", "testResults": "{}"}', 'https://hnvbmypjh9.execute-api.eu-central-1.amazonaws.com/prod/builds']
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']
- name: 'gcr.io/eloquent-hour-220409/test-results-reporter'
  args: ['PUT', './test-results.json', https://hnvbmypjh9.execute-api.eu-central-1.amazonaws.com/prod/builds ]  
  env:
    - 'BUILD=$BUILD_ID'
    - 'REPO=$REPO_NAME'
